### ISSUE TITLE
爬取完成,保存失败

### ISSUE THREAD

**Issue by qqblack** [skytruine/OSpider#1]
爬取完成后,就开始保存数据,这时候程序会闪退

**需要在程序目录新建一个 results文件夹,完美解决**

**Comment by skytruine** [comment]
感谢反馈，本问题将在1.0.2总得到解决，使得results文件夹不再是必须。

**Comment by skytruine** [comment]
发现上传的文件中没有results目录，已经在1.0.1基础上更正。
