### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by chenchenliux** [skytruine/OSpider#2]
看pdf，三百多秒才四千多个POI，这效率也太差了吧。另啥时候github变成推软件不放源码的地方了

**Comment by chenchenliux** [comment]
看pdf，三百多秒才四千多个POI，这效率也太差了吧。另啥时候github变成推软件不放源码的地方了

**Comment by skytruine** [comment]
不同机器测试效率不同，一台机器每分钟上千吧，一台10000w+分钟



---原始邮件---
发件人: "chenchenliux"<notifications@github.com&gt;
发送时间: 2019年12月31日(周二) 上午9:11
收件人: "skytruine/OSpider"<OSpider@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [skytruine/OSpider] 速度慢 (#2)



看pdf，三百多秒才四千多个POI，这效率也太差了吧。另啥时候github变成推软件不放源码的地方了

**Comment by skytruine** [comment]
速度上，下几个版本做一次大升级。慢慢做吧，能解决一部分人的需求，好用就成。



---原始邮件---
发件人: "chenchenliux"<notifications@github.com&gt;
发送时间: 2019年12月31日(周二) 上午9:11
收件人: "skytruine/OSpider"<OSpider@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [skytruine/OSpider] 速度慢 (#2)



看pdf，三百多秒才四千多个POI，这效率也太差了吧。另啥时候github变成推软件不放源码的地方了
